# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib doubletrs, .registration = TRUE
NULL

#' Build doublets from dgCMatrix slots and 1-based parent cell indices
#' (drawn in R, so `set.seed()` controls them). Returns the doublet matrix
#' slots.
#' @noRd
rs_build_doublets <- function(i, p, x, n_genes, n_cells, cell_a, cell_b, threads) .Call(wrap__rs_build_doublets, i, p, x, n_genes, n_cells, cell_a, cell_b, threads)

#' k nearest neighbours of the first `n_real` rows, 1-based.
#' @noRd
rs_find_neighbors <- function(pcs, n_real, k, threads) .Call(wrap__rs_find_neighbors, pcs, n_real, k, threads)

#' pANN for the first `n_real` rows.
#' @noRd
rs_compute_pann <- function(pcs, n_real, k, threads) .Call(wrap__rs_compute_pann, pcs, n_real, k, threads)

#' pANN for the first `n_real` rows at each k in `ks`: an n_real x length(ks)
#' matrix.
#' @noRd
rs_pann_sweep <- function(pcs, n_real, ks, threads) .Call(wrap__rs_pann_sweep, pcs, n_real, ks, threads)

# nolint end
